tasks:
  - name: Boot
    init: make hasura-install && echo 'export DOCKER_COMPOSE_TARGET=gitpod' >> ~/.bashrc && export DOCKER_COMPOSE_TARGET=gitpod
    command: open README.md && make boot


# Exposed services:
ports:
 - name: Hasura GraphQL APIs
   description: Runs the Hasura Engine APIs
   port: 8080
   visibility: public # Auth issues if private
   onOpen: ignore
 - name: Adminer
   description: Runs Adminer database Web Client
   port: 8081
   visibility: public
   onOpen: ignore
 - name: Hasura Console
   description: Runs the Hasura Web Console
   port: 9695
   visibility: public
   onOpen: open-preview
 - name: Hasura CLI APIs
   description: Runs the Hasura CLI APIs
   port: 9693
   visibility: public # Problems reaching the Hasura API if private
   onOpen: ignore
 - name: Postgres
   port: 5432
   onOpen: ignore
    
vscode:
 extensions:
   - ms-azuretools.vscode-docker
   - mtxr.sqltools
   - mtxr.sqltools-driver-pg
   - esbenp.prettier-vscode
   - darkriszty.markdown-table-prettify
   - Codeium.codeium
   - eamodio.gitlens
